import "./globals.css";
import Header from "./components/Header";
import Categories from "./components/Categories";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import BrandSlider from "./components/BrandSlider";

export const metadata = {
  title: "Ilan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Categories />
    
        {children}
      </body>
    </html>
  );
}
